### ISSUE TITLE
Crontab start broken in 1.0

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-scripts#43]
With 1.0 (last confirmed using 1.0.0-beta.6) the crontab entry `installLisk.sh` creates to start lisk `@reboot` does not work any more. 

No error is logged:
```
√ Postgresql started successfully.
√ Lisk started successfully.
√ Lisk is running as PID: 1255
Current Block Height:   48247
```

However the application always runs into a fatal error:

```
[FTL] 2018-04-23 14:06:12 | error: no PostgreSQL user name specified in startup packet
    at Connection.parseE (/home/lisk/lisk-1.0.0-beta.6-Linux-x86_64/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/home/lisk/lisk-1.0.0-beta.6-Linux-x86_64/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/home/lisk/lisk-1.0.0-beta.6-Linux-x86_64/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
[inf] 2018-04-23 14:06:13 | Socket Cluster ready for incoming connections
[dbg] 2018-04-23 14:06:13 | Worker pid 1391 started
[WRN] 2018-04-23 14:06:13 | Peer INSERT error: code: 4200, message: Failed to check if peer is already present, description: Procedure list not registered on WAMPServer.
                        Available commands: [object Object] on peer 206.189.83.206:5001
[WRN] 2018-04-23 14:06:13 | Peer INSERT error: code: 4200, message: Failed to check if peer is already present, description: Procedure list not registered on WAMPServer.
                        Available commands: [object Object] on peer 110.143.155.171:5001
[WRN] 2018-04-23 14:06:13 | Peer INSERT error: code: 4200, message: Failed to check if peer is already present, description: Procedure list not registered on WAMPServer.
                        Available commands: [object Object] on peer 206.189.152.108:5001
[WRN] 2018-04-23 14:06:14 | Peer INSERT error: code: 4200, message: Failed to check if peer is already present, description: Procedure list not registered on WAMPServer.
                        Available commands: [object Object] on peer 159.203.47.207:5001
```

Running `bash lisk.sh start` works.

**Comment by fchavant** [comment]
This is due to `.db.user` being set to the empty string in [config.json](https://github.com/LiskHQ/lisk/blob/v1.0.0-beta.6/config.json#L18) and the code defaulting to `process.env.USER` ([link](https://github.com/LiskHQ/lisk/blob/v1.0.0-beta.6/db/index.js#L95)) which is not set when using cron.
